### ISSUE TITLE
Secure neonwallet.com with SSL/TLS

### ISSUE THREAD

**Issue by brianlenz** [CityOfZion/neon-wallet-website#1]
I'd recommend serving the neonwallet.com website with TLS. It looks like it's not possible to do directly with GitHub pages:

https://github.com/isaacs/github/issues/156
https://gist.github.com/coolaj86/e07d42f5961c68fc1fc8

A workaround would be to use Cloudflare and host the neonwallet.com DNS there. Then, Cloudflare will handle TLS termination and proxy all requests through to the origin GitHub pages.

Cloudflare is really easy to setup and provides some other caching and CDN benefits (though GitHub pages probably does some of this similarly).

Here's a quick guide to setting up Cloudflare for use with GitHub pages:

https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

This will be particularly useful in light of Google's announcement that all non-HTTPS pages will be marked as "Not secure" in Chrome starting in July 2018:

https://www.theverge.com/2018/2/8/16991254/chrome-not-secure-marked-http-encryption-ssl

**Comment by comountainclimber** [comment]
@brianlenz thanks for taking the time to write up this detailed issue and attach these resources. Definitely looking to investigate/implement a solution to this issue as soon as possible

**Comment by brianlenz** [comment]
Cool, let me know if I can help!

**Comment by mhuggins** [comment]
It's possible with GitHub Pages now, we should get this going: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by comountainclimber** [comment]
@mhuggins @brianlenz looks like all we need to is update the `A` record with our DNS

<img width="773" alt="screen shot 2018-05-02 at 8 42 28 am" src="https://user-images.githubusercontent.com/13072035/39530012-42945e4e-4de5-11e8-8e53-09b407d8728d.png">

🎉

**Comment by comountainclimber** [comment]
https://neonwallet.com/ 👯
