### ISSUE TITLE
"Latest release information~" text is misaligned

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet-website#3]
**Browser:**
Chrome 65.0.3325.146 (64 bit)

![latest_release_misaligned](https://user-images.githubusercontent.com/8177587/37305371-8648119a-2634-11e8-86b7-6766bf64bb3e.png)

**Comment by comountainclimber** [comment]
@drptbl https://github.com/CityOfZion/neon-wallet-website/releases/tag/v0.1.1 thanks again
