### ISSUE TITLE
Error 408 while getting Linux icon image

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet-website#4]
**Browser:**
Chrome 65.0.3325.146 (64 bit)

![neonwalletlinuxiconsmissing](https://user-images.githubusercontent.com/8177587/37305641-672fb2e4-2635-11e8-8add-96a21e03b9e3.PNG)
![console](https://user-images.githubusercontent.com/8177587/37305651-6ea12882-2635-11e8-8f45-bf5ca59cf1a3.png)

**Comment by drptbl** [comment]
Couldn't reproduce this issue on Win 10 using IE11 and Edge + Chrome and Safari on iPhone 6S.
Occurs only on Windows 10 and Chrome browser.

**Comment by comountainclimber** [comment]
I cant reproduce this one one on Chrome with Windows 10 🙁

**Comment by drptbl** [comment]
@comountainclimber This is so weird. And I'm not sure how can I help further to get it fixed to be honest.

If I go to that url directly from browser on new tab:
http://neonwallet.com/static/media/linux-logo.993d981b.png
It just works and loads correctly.

But if it's referenced from http://neonwallet.com/ - I'm always getting a timeout (408) on this image.

I'm like - ¯\_(ツ)_/¯. Sorry.

**Comment by comountainclimber** [comment]
@drptbl No problem! I have a windows 10 machine and tried a couple scenarios to reproduce including chrome throttle down in dev tools. still couldnt get the 408. 

Again really happy for your input and opening of these issues!
