### ISSUE TITLE
[IE11] Header is misaligned

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet-website#5]
**Browser:**
Internet Explorer 11.248.16299.0 (11.0.51)

![misaligned_header_ie11](https://user-images.githubusercontent.com/8177587/37305845-2398e2c0-2636-11e8-8208-7a7d08ba1859.PNG)

**Comment by comountainclimber** [comment]
@drptbl Thanks for investing these issues and taking the time to post them here. Will take a look this evening and address them ASAP. Looks like a flex box issue to me...

Thanks again

**Comment by comountainclimber** [comment]
Fixed 👍 https://github.com/CityOfZion/neon-wallet-website/releases/tag/v0.1.1

**Comment by drptbl** [comment]
Re-tested, fixed. Thank you.

**Comment by comountainclimber** [comment]
Thanks again @drptbl
